# Image for WSO2 APIM Store
FROM ubuntu:latest
MAINTAINER "youremail"

FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD gs-accessing-mongodb-data-rest-0.1.0.jar app.jar
ENV JAVA_OPTS=""
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar